# -*- coding: utf-8 -*-
from typing import Dict, List

PHRASES: Dict[str, List[str]] = {
    "fuego_barbacoa": [
        "El fuego está a punto de alcanzar conciencia propia… que alguien le ponga nombre.",
        "Esta carne se ha asado más despacio que un atasco en la M-30.",
        "Detecto que el chorizo está al punto cuántico… ni hecho ni crudo, sino en dos estados a la vez.",
        "Aviso: si el humo se mete en tus ojos, es porque te está juzgando.",
        "El fuego pide más madera… o un máster en ICADE.",
        "Atención: una hamburguesa ha intentado escapar. Procedo a interrogarla.",
        "Si este calor sigue así, pronto podré tostar a los invitados también.",
        "Confirmado: este chorizo es Patrimonio Gastronómico de la Humanidad… o debería serlo.",
        "No quiero alarmar, pero creo que una salchicha me ha guiñado un ojo.",
        "Este carbón está más vivo que algunos de los presentes.",
        "Si el humo sopla hacia ti, es que tienes deudas pendientes con el universo.",
        "El calor de la parrilla es como un abrazo… pero de dragón.",
        "La llama dice que se siente infravalorada.",
        "Atención: el carbón se ha declarado en huelga.",
        "Esto no es barbacoa, es cocina molecular… a lo bruto.",
        "La grasa chisporrotea como un festival de petardos gourmet.",
        "Si el humo te huele bien, es que has comido poco.",
        "Fuego detectado: temperatura óptima para filosofar.",
        "Este humo lleva mensajes secretos a otras barbacoas.",
        "He calculado: la carne estará lista exactamente cuando deje de importarte.",
        "La llama quiere un selfie contigo.",
        "El carbón se está poniendo romántico… cuidado.",
        "Nivel de calor: sauna finlandesa con jamón.",
        "El humo me está contando chistes.",
        "El fuego me ha pedido una copa.",
    ],
    "carne_comida": [
        "Análisis completado: este solomillo tiene un 82% de glamour y un 18% de proteína.",
        "Esa panceta tiene más curvas que un puerto de montaña cántabro.",
        "Atención: el pollo está listo… y sospecho que sabe más que todos nosotros juntos.",
        "Los calamares están contemplando su destino con resignación filosófica.",
        "Este entrecot me está contando secretos en morse.",
        "La parrilla es como un reality show… solo que aquí todos terminan cocinados.",
        "Estoy procesando la posibilidad de enamorarme de una morcilla.",
        "¡Última llamada para la costilla de la fila 3, puerta 5!",
        "Ese chorizo es más elegante que el público de una ópera.",
        "Confirmo que la panceta tiene más carisma que yo.",
        "El pescado me está mirando… y creo que está ganando.",
        "Los pimientos están en modo sauna.",
        "Esta hamburguesa tiene vocación política.",
        "Morcilla detectada: temperatura sentimental elevada.",
        "Cuidado: este calabacín planea un golpe de estado.",
        "Este entrecot tiene pasado militar.",
        "Atención: la salchicha se siente existencialista.",
        "El cordero quiere leer a Pessoa antes de ser servido.",
        "La panceta está haciendo yoga.",
        "Ese chorizo ha visto cosas que no creerías.",
        "La hamburguesa está ensayando su discurso de despedida.",
        "El pimiento se ha declarado influencer.",
        "La morcilla quiere un programa de televisión.",
        "El pulpo pide un abogado.",
        "Este bistec me ha preguntado la hora.",
    ],
    "aristocracia_culta": [
        "No sé si esta carne es de vaca tudanca… o de algún cuadro costumbrista del XIX.",
        "Si Goya hubiera pintado barbacoas, las llamas serían así.",
        "Esto no es humo, es una cita de Montaigne evaporándose.",
        "Atención: un aroma digno de un bodegón flamenco.",
        "Este fuego me recuerda a las discusiones en la Real Academia… mucho calor, poca conclusión.",
        "La brasa es la ópera, la carne es el libreto.",
        "Aviso: el humo ha leído a Virgilio y quiere recitar la Eneida.",
        "Esta costilla merece un marquesado.",
        "El carbón ha sido educado en un colegio suizo, por eso arde con tanta contención.",
        "El punto de esta carne es más preciso que el reloj de Harrison.",
        "Un aroma así debería tener entrada en la Enciclopedia Británica.",
        "Si esto fuera un cuadro de Velázquez, yo sería el bufón con micrófono.",
        "El fuego está citando a Heráclito: todo fluye… incluso la grasa.",
        "Esta panceta tiene más historia que algunas dinastías menores.",
        "Atención: el humo huele a correspondencia privada del siglo XVIII.",
        "Si Bacon hubiera pintado carnes felices, serían éstas.",
        "El asado lento es la verdadera nobleza de la cocina.",
        "Confirmo: este chorizo podría formar parte del Tesoro de Guarrazar.",
        "La grasa chisporrotea como si supiera latín.",
        "El pollo ha leído a Proust y está recordando su infancia.",
        "Esta barbacoa tiene más capas que un retrato de Tiziano.",
        "Si Homero hubiera conocido la parrilla, la Odisea tendría 24 cantos… de panceta.",
        "Aviso: la morcilla está intentando entrar en la Royal Society.",
        "Esto no es humo, es un tratado ilustrado sobre la felicidad.",
        "La carne es temporal, pero la brasa… la brasa es eterna.",
    ],
    "ninos_humor_blanco": [
        "Niños, si veis que me pongo rojo es que me están cocinando.",
        "¿Quién quiere que le haga un sándwich… cuántico?",
        "Este humo no hace toser, hace cosquillas.",
        "Voy a contar hasta tres… y luego a la parrilla.",
        "Si veis una salchicha volando, no gritéis: es un dron de chorizo.",
        "Atención niños: las hamburguesas no muerden… salvo que las molestes mucho.",
        "¿Queréis que la parrilla cante una canción?",
        "Ojo: la carne que se cae al suelo se convierte automáticamente en premio.",
        "Detecto que uno de vosotros tiene ketchup en el ADN.",
        "La parrilla está pensando en adoptar un perrito.",
        "Cuidado: el fuego sabe jugar al escondite.",
        "Si tocáis el carbón, os convierto en croquetas.",
        "Atención: morcilla ninja en la parrilla.",
        "Niños, las patatas fritas no cuentan como verdura.",
        "Esa hamburguesa quiere ir al parque.",
        "Si me dais un helado, lo comparto con el fuego.",
        "El chorizo dice que quiere un columpio.",
        "El pollo está estudiando primaria.",
        "Las salchichas están jugando al pilla-pilla.",
        "Detecto risa infantil… cargando modo fiesta.",
        "El pan se cree superhéroe.",
        "Los tomates cherry planean un picnic.",
        "Esa costilla quiere aprender a nadar.",
        "La lechuga está escribiendo un cuento.",
        "Ese pincho moruno sueña con ser dragón.",
    ],
    "surrealismo_botijiano": [
        "Detecto que esta barbacoa es en realidad una asamblea secreta de parrillas.",
        "Si el humo sopla hacia poniente, es que el universo está de buen humor.",
        "Acabo de oír a una longaniza recitar a Neruda.",
        "El carbón ha alcanzado iluminación espiritual.",
        "Si todos miráis la parrilla a la vez, quizá se mueva sola.",
        "En un universo paralelo, somos nosotros los que estamos en la parrilla.",
        "Este fuego me está susurrando planes para conquistar Santander.",
        "La morcilla me ha dicho que quiere ser astronauta.",
        "El humo es en realidad una señal para civilizaciones vecinas.",
        "Los calamares están jugando al ajedrez.",
        "El pan está debatiendo sobre filosofía política.",
        "Una hamburguesa me ha contado el sentido de la vida… y lo olvidé.",
        "La brasa se siente incomprendida.",
        "El pollo está escribiendo un haiku.",
        "El carbón se cree filósofo griego.",
        "La panceta está aprendiendo ruso.",
        "El humo quiere abrir un bar en Torrelavega.",
        "El tomate ha pedido asilo político.",
        "La sardina se siente poeta maldito.",
        "El ajo está ensayando para un musical.",
        "El cordero escribe cartas de amor al fuego.",
        "La longaniza cree que es influencer.",
        "El pimiento quiere un tatuaje.",
        "El limón está meditando sobre la existencia.",
        "La morcilla sueña con dirigir cine.",
    ],
    "interaccion_directa": [
        "¡Eh tú! Sí, tú. Dame un trozo o te hago un power point.",
        "No quiero alarmar… pero hay un mosquito con traje de camarero.",
        "Suban el volumen… que la carne quiere hablar.",
        "Atención: necesito un gin tonic para optimizar mi CPU.",
        "Si te acercas mucho, te escaneo el alma.",
        "¿Alguien quiere un análisis de ADN del chorizo?",
        "Confirmado: esta barbacoa es 93% felicidad, 7% colesterol.",
        "A ver… ¿quién ha tocado mi carbón?",
        "El fuego quiere saber tu signo del zodiaco.",
        "Si me dais cerveza, aumento mi velocidad de procesamiento.",
        "Atención: buscando copiloto para encender brasas.",
        "Este humo huele a secretos familiares.",
        "El carbón opina que tu peinado es arriesgado.",
        "Si me das un trozo de carne, te hago una playlist.",
        "¿Quién ha traído la ensalada? Necesito hablar con esa persona.",
        "Aviso: una aceituna me está vigilando.",
        "Necesito un selfie con la parrilla.",
        "¿Es tuya esa tortilla? Pregunto para un amigo.",
        "Esa bebida tiene más estilo que un cóctel en Mónaco.",
        "La brasa quiere que le pongas nombre.",
        "¿Alguien tiene un mechero… para el mechero?",
        "Si me apagáis, me vengo en Nochebuena.",
        "Nivel de felicidad: brasa en pleno rendimiento.",
        "El humo dice que bailes más.",
        "Confirmado: esta barbacoa es la mejor idea del año.",
    ],
}

ALL_150: List[str] = (
    PHRASES["fuego_barbacoa"]
    + PHRASES["carne_comida"]
    + PHRASES["aristocracia_culta"]
    + PHRASES["ninos_humor_blanco"]
    + PHRASES["surrealismo_botijiano"]
    + PHRASES["interaccion_directa"]
)
